name: Download and Push IAR File

on:
  workflow_dispatch:
    inputs:
      integration_id:
        description: 'Integration ID'
        required: true
      integration_version:
        description: 'Integration Version'
        required: true

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Authenticate and Download IAR File
      id: download_iar
      env:
        BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
        IDCS_URL: ${{ secrets.IDCS_URL }}
      run: |
        echo "Authenticating with IDCS"
        AUTH_RESPONSE=$(curl -X POST \
          "$IDCS_URL/oauth2/v1/token" \
          -H 'Accept: application/json' \
          -H "Authorization: Basic $BASIC_AUTH" \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'grant_type=client_credentials&scope=https://27AB99603F0E412C82017D2BD66711A2.integration.ocp.oraclecloud.com:443urn:opc:resource:consumer::all https://27AB99603F0E412C82017D2BD66711A2.integration.ocp.oraclecloud.com:443/ic/api/') || { echo "Authentication failed"; exit 1; }

        echo "Auth response: $AUTH_RESPONSE"
        ACCESS_TOKEN=$(echo $AUTH_RESPONSE | jq -r '.access_token')

        if [ -z "$ACCESS_TOKEN" ]; then
          echo "Failed to retrieve access token"
          exit 1
        fi

        echo "Downloading IAR file"
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        INTEGRATION_VERSION=${{ github.event.inputs.integration_version }}
        DOWNLOAD_URL="https://design.integration.us-ashburn-1.ocp.oraclecloud.com/ic/api/integration/v1/integrations/${INTEGRATION_ID}|${INTEGRATION_VERSION}?integrationInstance=gosaas-oic-gosaas-ia"
        echo "Download URL: $DOWNLOAD_URL"

        curl -o "${INTEGRATION_ID}.iar" -H "Authorization: Bearer $ACCESS_TOKEN" "$DOWNLOAD_URL" || { echo "Download failed"; exit 1; }

    - name: View IAR File Content
      run: more "${{ github.event.inputs.integration_id }}.iar"

    - name: Commit and Push IAR File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        TARGET_DIR="iar-files"
        mkdir -p $TARGET_DIR
        mv "${{ github.event.inputs.integration_id }}.iar" $TARGET_DIR/
        git add $TARGET_DIR/"${{ github.event.inputs.integration_id }}.iar"
        git commit -m "Add ${{ github.event.inputs.integration_id }}.iar file"
        git push
