name: Download and Push IAR File

on:
  workflow_dispatch:
    inputs:
      integration_id:
        description: 'Integration ID'
        required: true
      integration_version:
        description: 'Integration Version'
        required: true

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Download IAR File
      id: download_iar
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
      run: |
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        INTEGRATION_VERSION=${{ github.event.inputs.integration_version }}
        DOWNLOAD_URL="https://design.integration.us-ashburn-1.ocp.oraclecloud.com/ic/api/integration/v1/integrations/${INTEGRATION_ID}|${INTEGRATION_VERSION}?integrationInstance=gosaas-oic-gosaas-ia"
        echo "Download URL: $DOWNLOAD_URL"

        curl -o "${INTEGRATION_ID}.iar" -H "Authorization: Bearer $ACCESS_TOKEN" "$DOWNLOAD_URL" || { echo "Download failed"; exit 1; }

        # List files for debugging
        ls -l
        echo "Downloaded IAR file:"
        ls -l "${INTEGRATION_ID}.iar"

    - name: Verify IAR File Download
      run: |
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        if [ ! -f "${INTEGRATION_ID}.iar" ]; then
          echo "IAR file not found!"
          exit 1
        fi

    - name: Commit and Push IAR File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        TARGET_DIR="path/to/store/in/repo"
        mkdir -p $TARGET_DIR
        mv "${INTEGRATION_ID}.iar" $TARGET_DIR/
        echo "Moved IAR file to target directory:"
        ls -l $TARGET_DIR

        # Touch the file to ensure its timestamp is updated
        touch $TARGET_DIR/"${INTEGRATION_ID}.iar"

        # Debugging: Show the git status and diff
        git status
        git diff $TARGET_DIR/"${INTEGRATION_ID}.iar"

        git add -f $TARGET_DIR/"${INTEGRATION_ID}.iar"
        git commit -m "Update ${INTEGRATION_ID}.iar file"
        git push

    - name: Create and Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        INTEGRATION_VERSION=${{ github.event.inputs.integration_version }}
        TAG_NAME="${INTEGRATION_ID}-${INTEGRATION_VERSION}"
        git tag $TAG_NAME
        git push origin $TAG_NAME
