name: Download and Push IAR File

on:
  workflow_dispatch:
    inputs:
      integration_id:
        description: 'Integration ID'
        required: true
      integration_version:
        description: 'Integration Version'
        required: true

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Download IAR File
      id: download_iar
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
      run: |
        INTEGRATION_ID=${{ github.event.inputs.integration_id }}
        INTEGRATION_VERSION=${{ github.event.inputs.integration_version }}
        DOWNLOAD_URL="https://design.integration.us-ashburn-1.ocp.oraclecloud.com/ic/api/integration/v1/integrations/${INTEGRATION_ID}|${INTEGRATION_VERSION}?integrationInstance=gosaas-oic-gosaas-ia"
        echo "Download URL: $DOWNLOAD_URL"

        curl -o "${INTEGRATION_ID}.iar" -H "Authorization: Bearer $ACCESS_TOKEN" "$DOWNLOAD_URL" || { echo "Download failed"; exit 1; }

    - name: Commit and Push IAR File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        TARGET_DIR="iar-files/repo"
        mkdir -p $TARGET_DIR
        mv "${{ github.event.inputs.integration_id }}.iar" $TARGET_DIR/
        git add $TARGET_DIR/"${{ github.event.inputs.integration_id }}.iar"
        git commit -m "Add ${{ github.event.inputs.integration_id }}.iar file"
        git push
