name: Download and Push IAR File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL to download the IAR file'
        required: true

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate and Download IAR File
      id: download_iar
      env:
        BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
        IDCS_URL: ${{ secrets.IDCS_URL }}
      run: |
        AUTH_RESPONSE=$(curl -X POST \
          "$IDCS_URL/oauth2/v1/token" \
          -H 'Accept: application/json' \
          -H "Authorization: Basic $BASIC_AUTH" \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'grant_type=client_credentials&scope=https://27AB99603F0E412C82017D2BD66711A2.integration.ocp.oraclecloud.com:443urn:opc:resource:consumer::all https://27AB99603F0E412C82017D2BD66711A2.integration.ocp.oraclecloud.com:443/ic/api/')

        ACCESS_TOKEN=$(echo $AUTH_RESPONSE | jq -r '.access_token')

        curl -o downloaded.iar -H "Authorization: Bearer $ACCESS_TOKEN" \
          "${{ github.event.inputs.file_url }}"

    - name: Commit and Push IAR File
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        mv downloaded.iar path/to/store/in/repo/
        git add path/to/store/in/repo/downloaded.iar
        git commit -m "Add downloaded IAR file"
        git push
